### ISSUE TITLE
How to interpret pipeline results

### ISSUE THREAD

**Issue by noyessie** [oaqa/bioasq#1]
Hi,

according to installation guide, I installed bioasq. But I don't understant the information in `result` folder. This folder contains 4 files:

1. 652940988b935f152856ec403b6fdc6f92f7db50fd74f589efa30697b63824fb
2. answer-collective-score-predict-liblinear.tsv
3. answer-score-predict-liblinear.tsv
4. answer-type-predict-liblinear-null.tsv

Please anyone can't help me to understand these files and their contains.

Thanks in advance.

**Comment by ziy** [comment]
Two types of “results” files are generated: the one with the hash-like filename is the output file complying the the BioASQ submission specification for years before 2016, the others are intermediate files for debugging purposes only.

A handy way to look for the descriptor that specifies these files is to grep the filenames like within the src/main/resources directory:

```
grep -R 'answer-score-predict-liblinear.tsv' src/main/resources
```

Then you will be able to locate the actual Java code that creates each file and also the format it uses. For example, you will see this line is grepped from the descriptor:

```
src/main/resources/bioqa/answer/score/liblinear-predict.yaml:feature-file: result/answer-score-predict-liblinear.tsv
```

Then the descriptor indicates it is derived from a series of “parent” descriptors:

```
inherit: bioqa.answer.score.classifier-predict
inherit: baseqa.answer.score.classifier-predict
inherit: baseqa.learning_base.classifier-predict
```

The final “base” descriptor shows you may find the actual Java code from

```
class: edu.cmu.lti.oaqa.baseqa.learning_base.ClassifierPredictor
```

-- 
Zi Yang
PhD Candidate
Language Technologies Institute
School of Computer Science
Carnegie Mellon University
HP: http://www.cs.cmu.edu/~ziy <http://www.cs.cmu.edu/~ziy>

**Comment by noyessie** [comment]
Thank's @ziy
